#! /bin/bash

# iqtree.sh

set -e
set -u
set -o pipefail

# ------------------------------------------------------------------------------

# Generate tree of study accession samples

# Arguments to script:
# study accession, fasta file directory, cluster file directory, output location

# Input:
# fasta file of samples from one study accession, 'cluster' file generated by R - list of samples that fall into 'clusters', i.e. within 50 SNP distance

# Main steps:
# filter fasta file based on cluster file - only retain samples in this cluster file
# run IQ tree on filterd fasta file
# move file to right place

# Output:
# newick file of study accession tree

# RUN
# Assume run from ~/transmission :
# shell_scripts/iqtree.sh <study_accession>   <fasta_input_file>                                <cluster_file>                    <newick_output_dir>
# shell_scripts/iqtree.sh PRJEB7669           fasta/PRJEB7669.filt.val.gt.g.snps.fa             metadata/PRJEB7669.clusters       newick/
# shell_scripts/iqtree.sh KARONGA             fasta/KARONGA.filt.val.gt.g.snps.fa               metadata/KARONGA.clusters         newick/

# ------------------------------------------------------------------------------

# Setup

# Variables
study_accession=${1?Error: enter sudy accession number e.g. PRJEB7669}

# Directories
# fasta_dir=${2?Error: enter directory of input fasta file}
# cluster_file_dir=${3?Error: enter directory of cluster file}
newick_output_dir=${4?Error: enter where iqtree results are to be saved}
tmp_dir=tmp/


# Files
# fasta_input_file=${fasta_dir}${study_accession}.filt.val.gt.g.snps.fa
fasta_input_file=${2?Error: enter name of input fasta file}
fasta_filtered_file=${fasta_input_file}.filt
# cluster_file=${cluster_file_dir}${study_accession}.clusters
cluster_file=${3?Error: enter name of cluster file}
tmp_cluster_ids_file=${tmp_dir}${study_accession}.clustered_samps

# Directories
fasta_dir=`dirname ${fasta_input_file}`/

# Parameters

# Commands

# Print arguments
printf "\n"
echo "Arguments:"
printf "\n"
echo ${study_accession}
echo ${newick_output_dir}
echo ${tmp_dir}
echo ${fasta_input_file}
echo ${fasta_filtered_file}
echo ${cluster_file}
echo ${tmp_cluster_ids_file}

printf "\n"

# Make output dir if not exist
if [ ! -d ${newick_output_dir} ]; then
    mkdir ${newick_output_dir}
fi

# Make tmp file if not exist
if [ ! -d ${tmp_dir} ]; then
    mkdir ${tmp_dir}
fi

# ------------------------------------------------------------------------------

# Pull just list of samples from cluster file
cut -f1 ${cluster_file} | tail -n +2 > ${tmp_cluster_ids_file}

# ------------------------------------------------------------------------------

# Filter fasta file - remove samples that do not meet the threshold SNP distance for cluster inclusion
# n.b. second 'grep' gets rid of 'line separator' - some bloody thing that grep puts in where something is missing i.e. the samples that are excluded

grep -A1 -f ${tmp_cluster_ids_file} ${fasta_input_file} | grep -v "\--" > ${fasta_filtered_file}


# ------------------------------------------------------------------------------

# Run iqtree:

echo "Running iqtree on ${fasta_filtered_file}"
echo "Number of samples: `grep ">" ${fasta_filtered_file} | wc -l`"
# Run tree
iqtree -s ${fasta_filtered_file} -m GTR+G -nt AUTO

# Move output files to correct place
mv ${fasta_dir}*.iqtree ${fasta_dir}*.treefile ${fasta_dir}*.log ${newick_output_dir}

# ------------------------------------------------------------------------------

# Clean up
rm ${tmp_cluster_ids_file}
rm ${fasta_dir}*.bionj
rm ${fasta_dir}*.mldist
rm ${fasta_dir}*.uniqueseq.phy
