#! /bin/bash

# plink_dist_and_pca.sh

set -e
set -u
set -o pipefail

# ------------------------------------------------------------------------------

# Get distance matrix generated by plink

# Adapted from:
# https://github.com/GaryNapier/Cluster_analysis/blob/master/tb-phylogeny-pipeline.py

# Arguments to script:
# study accession, vcf location, output location

# Input:
# filtered vcf file of name format: <study accession>.filt.val.gt.g.vcf.gz

# Main steps:
# run plink distance matrix, run plink pca

# Output:
# plink distance matix, plink pca

# RUN
# Assume run from ~/transmission :
# ./shell_scripts/plink_dist_and_pca.sh <study_accession>, <vcf_dir>, <output_dir>
# ./shell_scripts/plink_dist_and_pca.sh PRJEB7669 ~/vcf/ dist_and_pca/

# ------------------------------------------------------------------------------

# Setup

# Variables
study_accession=${1}

# Directories
vcf_dir=${2}
output_dir=${3}

# Files
vcf_input_file=${vcf_dir}${study_accession}.filt.val.gt.g.vcf.gz
output_dist_file=${output_dir}${study_accession}.dist
output_pca_file=${output_dir}${study_accession}.pca

# Parameters

# Commands


# Print arguments
printf "\n"
echo "Arguments:"
printf "\n"
echo ${study_accession}
echo ${vcf_dir}
echo ${output_dir}
echo ${vcf_input_file}
echo ${output_dist_file}
echo ${output_pca_file}
printf "\n"

# Make output dir if not exist
if [ ! -d ${output_dir} ]; then
    mkdir ${output_dir}
fi

# ------------------------------------------------------------------------------

# ----------------------
# Do plink dist and pca
# ----------------------

printf "\n"
echo "Running plink --distance square:"
printf "\n"

plink --bcf ${vcf_input_file} --distance square --double-id --allow-extra-chr --out ${output_dist_file}

printf "\n"
echo "Running plink --pca:"
printf "\n"

plink --bcf ${vcf_input_file} --pca --double-id --allow-extra-chr --out ${output_pca_file}

# plink --vcf ~/vcf/PRJEB7669.filt.val.gt.g.vcf.gz --mds-plot 10 eigendecomp --cluster --double-id --allow-extra-chr --out PRJEB7669.pca

echo "DONE"

# Should make files:

# <output_dir><study accession>.dist.dist
# <output_dir><study accession>.dist.dist.id
# <output_dir><study accession>.dist.log
# <output_dir><study accession>.dist.nosex
# <output_dir><study accession>.pca.eigenval
# <output_dir><study accession>.pca.eigenvec
# <output_dir><study accession>.pca.log
# <output_dir><study accession>.pca.nosex
